spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      # 默认用户名neo4j
      username: neo4j
      # 你的登录密码
      password: 123456

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB


